# permissions for end users to edit clusterlinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterlink-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cl-operator
    app.kubernetes.io/part-of: cl-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterlink-editor-role
rules:
- apiGroups:
  - cl.clusterlink.net
  resources:
  - clusterlinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cl.clusterlink.net
  resources:
  - clusterlinks/status
  verbs:
  - get
