---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cl.clusterlink.net
  resources:
  - clusterlinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cl.clusterlink.net
  resources:
  - clusterlinks/finalizers
  verbs:
  - update
- apiGroups:
  - cl.clusterlink.net
  resources:
  - clusterlinks/status
  verbs:
  - get
  - patch
  - update
