name: Create docker release and publish to ghcr

on:
  push:
    tags:
      - '*'

jobs:
  build_and_push_to_ghcr:
    name: Publish a new Docker images in ghcr
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.20']      
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: checkout
      uses: actions/checkout@v4
    - name: Run build
      run: make build
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push cl-dataplane image 
      run: |
        docker build -t ghcr.io/clusterlink-net/cl-dataplane:${{ github.ref }} .
        docker push ghcr.io/clusterlink-net/cl-dataplane:${{ github.ref }}
    - name: Build and push cl-controlplane image
      run: |
        docker build -t ghcr.io/clusterlink-net/cl-controlplane:${{ github.ref }} .
        docker push ghcr.io/clusterlink-net/cl-controlplane:${{ github.ref }}
    - name: Build and push cl-cgo-dataplane image 
      run: |
        docker build -t ghcr.io/clusterlink-net/cl-go-dataplane:${{ github.ref }} .
        docker push ghcr.io/clusterlink-net/cl-go-dataplane:${{ github.ref }}
    - name: Build and push gwctl image 
      run: |
        docker build -t ghcr.io/clusterlink-net/gwctl:${{ github.ref }} .
        docker push ghcr.io/clusterlink-net/gwctl:${{ github.ref }}
